frontend/pages/conexao.vue

Add manual errors verification

---

backend/app/mailers/application_mailer.rb
backend/app/models/conexao.rb
backend/app/views/application_mailer/conexao.html.erb
backend/spec/models/conexao_spec.rb
backend/spec/requests/conexoes_spec.rb
frontend/layouts/default.vue
frontend/pages/conexao.vue

Add conexao details

---

frontend/pages/inovacao.vue
frontend/plugins/services/fetch_pdis.js

remove integration with USP Multi

---

backend/app/controllers/company_updates_controller.rb
backend/app/models/company_patent.rb
backend/app/models/company_update_request.rb
backend/spec/requests/company_updates_spec.rb
frontend/components/CompanyForms/CompanyStep.vue
frontend/components/CompanyForms/companyStep/Patents.vue
frontend/components/CompanyForms/inputs/MultipleInputs.vue
frontend/components/CompanyForms/inputs/PairOfShortTextInput.vue
frontend/components/CompanyForms/inputs/PatentNameAndCode.vue
frontend/pages/empresas/atualizar/index.vue
frontend/store/company_forms/index.js
frontend/store/company_forms/patents.js

create new tab for patents

---

frontend/components/first_level/PeopleCardsRow.vue
frontend/pages/contato.vue

fix contact page with the new staff

---

backend/lib/tasks/mailer.rake

changing way of redefine delivered variable

---

backend/spec/requests/company_updates_spec.rb

mock app mailer to avoid sends in testing

---

frontend/components/first_level/home/Banner.vue

add maintenance alert when use global search

---

frontend/components/first_level/home/Banner.vue
frontend/components/first_level/home/InfoAuspin.vue
frontend/components/layout/Footer.vue

Add links to images

---

.github/workflows/kotlin-ci.yml
.github/workflows/notify_pr.yml
.github/workflows/ruby-ci.yml

setup github actions for monorepo

---

server/catalog/src/main/kotlin/br/usp/inovacao/hubusp/server/catalog/PatentSearchParams.kt
server/hub-app/src/main/kotlin/br/usp/inovacao/hubusp/server/app/modules/QueryParametersExtensions.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/configureDB.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/patentExtension.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogPatentRepositoryImplTest.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/PatentExtensionKtTest.kt

Signed-off-by: mariliatd <mariliatd@gmail.com>

Add text-based search for patents

---

frontend/components/SkillForms/BondStep.vue
frontend/components/SkillForms/PersonalStep.vue
frontend/plugins/services/update_skills.js

Fix skill update forms

---

.github/workflows/kotlin-ci.yml
.github/workflows/notify_pr.yml
.github/workflows/ruby-ci.yml

fix naming in CI files

---

frontend/pages/competencias/atualizar/index.vue
frontend/pages/competencias/atualizar/solicitar.vue
frontend/pages/empresas/atualizar/index.vue
frontend/pages/empresas/atualizar/solicitar.vue

Replace navigation texts to avoid abiguity

---

frontend/components/CompanyForms/IntroStep.vue

add explicit saying about portaria 7679/2021

---

frontend/modules/Catalog/components/ListAndDetails.vue

clear details card when data list changes

---

frontend/modules/Catalog/pages/educacao.vue

Co-authored-by: Luiz Carlos <luizcarlosdk@hotmail.com>

fix undefined reference in discipline card

---

backend/.gitignore
backend/app/controllers/conexoes_controller.rb
backend/app/mailers/application_mailer.rb
backend/app/views/application_mailer/conexao_confirmation.html.erb
backend/app/views/application_mailer/conexao_confirmation.text.erb
backend/spec/requests/conexoes_spec.rb

**AS** a user of ConexãoUSP
**I WANT** to receive a confirmation email
**SO THAT** I can be sure my data was recorded

Confirmation email for Conexão

---

backend/app/controllers/company_controller.rb
backend/spec/requests/company_updates_spec.rb

This PR fixes the tests that were failing in CI

fix failing errors in CI

---

caddy/Caddyfile.sti

Co-authored-by: Luiz Carlos <luizcarlosdk@hotmail.com>

fix typos in Caddyfile.sti

---

frontend/pages/competencias/atualizar/solicitar.vue
frontend/pages/empresas/atualizar/solicitar.vue

Disable request token button util the completion of request

---

server/Assistfile.json
server/Dockerfile
server/curatorship/build.gradle.kts
server/curatorship/gradle.properties
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/CliCommandTest.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/Configuration.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/Mailer.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/SheetReadingException.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/SpreadsheetReader.kt
server/curatorship/src/main/resources/application.conf
server/hub-cli/build.gradle.kts
server/hub-cli/gradle.properties
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/Main.kt
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/commands/Test.kt
server/mailer/build.gradle.kts
server/mailer/gradle.properties
server/mailer/src/main/kotlin/br/usp/inovacao/hubusp/mailer/Mail.kt
server/mailer/src/main/kotlin/br/usp/inovacao/hubusp/mailer/Mailer.kt
server/settings.gradle.kts

**AS** a developer
**I WANT** to provide a platform for curatorship
**SO THAT** we have an easy development ahead

Scaffold curatorship

---

backend/app/controllers/company_updates_controller.rb
backend/app/mailers/application_mailer.rb
backend/app/views/application_mailer/confirmation_company_update.html.erb
backend/app/views/application_mailer/confirmation_company_update.text.erb
backend/spec/requests/company_updates_spec.rb

**AS** a user
**I WANT** to receive an email with the company form data
**SO THAT** I know it has been handled by the server

send confirmation email with new company update request

---

backend/config/initializers/campi.rb

Add new campus

---

backend/app/models/company.rb
backend/spec/models/company_spec.rb

Remove uniquess validation in corporate_name and aply to company cnpj

---

frontend/components/CompanyForms/companyStep/Base.vue

Avoid company to edit cnpj field into the forms

---

frontend/modules/Catalog/components/DropdownFilter.vue
frontend/modules/Catalog/components/MultipleFilters.vue
frontend/modules/Catalog/pages/empresas.vue

Add preselect filters using queryParams

---

frontend/layouts/default.vue

Co-authored-by: Luiz <luizcarlosdk@hotmail.com>

Add AUSPIN navbar

---

frontend/pages/conexao.vue

Add multiple option to demand knowledment area

---

frontend/pages/conexao.vue

Add multiple Choice expectation demand

---

backend/app/controllers/company_updates_controller.rb
backend/app/models/partner.rb

Add partner bond message error

---

frontend/pages/empresas/atualizar/index.vue

Co-authored-by: Luiz <luizcarlosdk@hotmail.com>

Scroll up when to show error message

---

frontend/components/CompanyForms/Stepper.vue

Fix not enough visible error

---

README.md

Add README to project root

---

frontend/modules/Catalog/components/BulletList.vue
frontend/modules/Catalog/components/NDText.vue
frontend/modules/Catalog/pages/competencias.vue
frontend/modules/Catalog/pages/empresas.vue
frontend/modules/Catalog/pages/iniciativas.vue

Co-authored-by: Luiz Carlos <luizcarlosdk@hotmail.com>

create initial version of NDText component

---

backend/app/controllers/company_updates_controller.rb
backend/spec/models/company_update_spec.rb
backend/spec/models/dna_usp_stamp_spec.rb
frontend/components/CompanyForms/DNAUSPStep.vue
frontend/components/CompanyForms/companyStep/Base.vue
frontend/components/CompanyForms/companyStep/Incubator.vue

A AUSPIN pediu para que indicássemos quais campos do formulário de atualização são obrigatórios.
Testamos um por um para ver quais são tolerados pela validação ou não e, se for impossível finalizar o formulário sem o preenchimento do campo, então colocamos um asterisco ao lado da label/descrição dele.

Mark required fields with asterisk

---

server/catalog/src/main/kotlin/br/usp/inovacao/hubusp/server/catalog/Initiative.kt
server/discovery/src/main/kotlin/br/usp/inovacao/hubusp/server/discovery/JourneyRecord.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/InitiativeModel.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImplTest.kt

Handle null url case

---

frontend/components/CompanyForms/Stepper.vue

Instead of using an (!)  i changed to an v-icon

---

frontend/components/CompanyForms/companyStep/Incubator.vue

Add a new option to incubator dropdown

---

frontend/pages/contato.vue

I added my profile picture to the Contact page of the website.

Add new contact photo

---

backend/app/models/company.rb
backend/app/models/company_datum.rb
backend/app/views/application_mailer/confirmation_company_update.html.erb
backend/app/views/application_mailer/confirmation_company_update.text.erb
backend/spec/models/company_datum_spec.rb
backend/spec/models/company_spec.rb
backend/spec/requests/company_spec.rb
backend/spec/requests/company_updates_spec.rb

Este pull-request resolve os problemas alertados pelos testes e pelo linter do backend, proveniente de mudanças errôneas na branch principal.

Revert backend changes

---

frontend/pages/contato.vue

Este _pull-request_ adiciona um novo membro ao corpo de desenvolvedores do site do Hub.

Add developer

---

frontend/components/CompanyForms/companyStep/Finance.vue
frontend/components/CompanyForms/companyStep/Investments.vue
frontend/components/CompanyForms/companyStep/Staff.vue

Este _pull-request_ adiciona alertas em seções do formulário de atualização do cadastro das empresas para enfatizar que os dados sensíveis não serão publicados.

Add unpublished sensitive data alert

---

frontend/modules/Catalog/pages/inovacao.vue

Foi adicionado um aviso de que a página de PDI está sob manutenção.

Add a warning message for PDI page

---

frontend/pages/empresas/atualizar/index.vue

- Adiciona um `prevent` ao pressionar o botão _enter_ no componente de campo de texto.

Fix reloading on enter key press at company update token submit 

---

frontend/components/UniversalAuspinBar.vue
frontend/layouts/default.vue

Este _pull-request_ tem, em resumo, as seguintes alterações:
- Modificações do layout padrão para a correção do posicionamento do menu do Hub.
- Modificação do componente `UniversalAuspinBar.vue` para corrigir o estilo e o posicionamento dos componentes da barra  superior do site, com base no site da AUSPIN.

AUSPIN bar layout and style fixes

---

backend/app/models/company.rb
backend/app/models/company_datum.rb
backend/app/views/application_mailer/confirmation_company_update.html.erb
backend/app/views/application_mailer/confirmation_company_update.text.erb
backend/spec/models/company_datum_spec.rb
backend/spec/models/company_spec.rb
backend/spec/requests/company_spec.rb
backend/spec/requests/company_updates_spec.rb
frontend/components/CompanyForms/companyStep/Base.vue
frontend/store/company_forms/company_data.js

Change cidade-sede multiple answers to one answer

---

backend/app/models/about_company.rb
backend/app/models/company_datum.rb
backend/app/models/company_update_request.rb
backend/app/models/dna_usp_stamp.rb
backend/app/models/investment.rb
backend/app/models/partner.rb
backend/app/models/revenue.rb
backend/app/models/staff.rb
backend/spec/models/about_company_spec.rb
backend/spec/models/company_datum_spec.rb
backend/spec/models/dna_usp_stamp_spec.rb
backend/spec/models/investment_spec.rb
backend/spec/models/partner_spec.rb
backend/spec/models/revenue_spec.rb
backend/spec/models/staff_spec.rb

The previous version of sheets creating was overwriting some data, so  fix the spaces between data

Arruma índice das colunas no backend

---

frontend/plugins/services/update_company.js

- Adiciona tradução para o erro "Bond inválido"

Corrige tradução de erro de vínculo

---

backend/app/controllers/company_updates_controller.rb
backend/app/models/about_company.rb
backend/config/routes.rb
frontend/components/CompanyForms/companyStep/About.vue
frontend/plugins/services/update_company.js
frontend/store/company_forms/about.js
frontend/store/company_forms/index.js

- Logo upload feature remains the same, this does not affect user's routine on company update form
- Instead of upload temporary logo file on any image input change, logo is now uploaded only on company update form submit

Fix logo upload technical debt

---

server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/Company.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyClassificationTranslator.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyClassificationValues.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyErrorRepository.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyRepository.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyUniquenessError.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyValidationError.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/RefreshCompany.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/UniquenessException.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/constraints.kt
server/curatorship/src/main/resources/messages_en.properties
server/curatorship/src/test/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyTest.kt
server/curatorship/src/test/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/CompanyTestHelp.kt
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/Main.kt
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/commands/curatorship/RefreshCompany.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogCompanyRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/configureDB.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/CompanyErrorRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/CompanyRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/CompanyModel.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/CompanyUniquenessErrorModel.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/CompanyValidationErrorModel.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogCompanyRepositoryImplTest.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/CompanyRepositoryImplTest.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/utils.kt

Add company spreadsheet Kotlin fetch support

---

backend/app/services/get_entities_service.rb

Rails was not recognizing the tab name for discipline, since rails will be legacy, this PR fix temporarily this bug for now.

Fix rails use of .env 

---

backend/app/services/get_entities_service.rb
server/catalog/src/main/kotlin/br/usp/inovacao/hubusp/server/catalog/Discipline.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/Discipline.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/DisciplineErrorRepository.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/DisciplineRepository.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/DisciplineUniquenessError.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/DisciplineValidationError.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/RefreshDiscipline.kt
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/constraints.kt
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/Main.kt
server/hub-cli/src/main/kotlin/br/usp/inovacao/hubusp/server/cli/commands/curatorship/RefreshDiscipline.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogDisciplineRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/configureDB.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/DisciplineErrorRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/curatorship/DisciplineRepositoryImpl.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/DisciplineModel.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/DisciplineUniquenessErrorModel.kt
server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/models/DisciplineValidationErrorModel.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogDisciplineRepositoryImplTest.kt
server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/journey/JourneyRepositoryImplTest.kt

Tentativa de realizar o fetch de disciplinas no kotlin

Kotlin Refresh Discipline

---

frontend/modules/Catalog/pages/empresas.vue
server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/Company.kt

Ao fazer o fetch, agora o kotlin altera o link para usar um que o frontend não tenha problema de entender

Fix companies logo

---

frontend/components/first_level/PeopleCardsRow.vue
frontend/pages/contato.vue

Remove the photos from contact page due to some photos giving 404 error (not found)

Renew contact page

---

frontend/nuxt.config.js

Create a temporality solution for analytics until Nuxt 2 its not being migrated to Nuxt 3

add gtag to Nuxt 2

---

frontend/layouts/default.vue
frontend/modules/Catalog/pages/empresas.vue

Change the company name to company DNA USP, as request by AUSPIN

Change name of empresa to empresas DNA USP

---

frontend/modules/Catalog/components/Panel.vue
frontend/modules/Catalog/pages/empresas.vue

This PR adds a visual counter to company main page showing how many companies DNA USP are registered

Add company counter to company page

---

server/curatorship/src/main/kotlin/br/usp/inovacao/hubusp/curatorship/sheets/Researcher.kt

The frontend researcher photo was not loading due to missing backend parse on URL.

Add function to format researcher photo URL on kotlin

---

server/mailer/src/main/kotlin/br/usp/inovacao/hubusp/mailer/Mail.kt
server/mailer/src/main/kotlin/br/usp/inovacao/hubusp/mailer/Mailer.kt

Closes #273
formatted with `ktfmt --kotlinlang-style`

server: mailer: Add support for emails with attachments

---

frontend/components/CompanyForms/CompanyStep.vue

frontend: CompanyForms/CompanyStep: Remove unused Patents import

---

frontend/components/CompanyForms/Stepper.vue

Closes #267 
> [!NOTE]
> That first line in the diff is the result of linting, it only changed the prop order lol

frontend: components/CompanyForms: Fix misaligned error popup

---

frontend/modules/Catalog/pages/educacao.vue

Closes #272
- remove offering period filter
- add offering status to the description of each discipline
("Sendo oferecida" // "Não está sendo oferecida no momento")

frontend: Remove 'offering period' filter
